require("prototypes/entity/trivial-smoke/IR3-particle-smoke")

require("prototypes/entity/optimized-particle/bronze-particle")
require("prototypes/entity/optimized-particle/copper-particle")
require("prototypes/entity/optimized-particle/glass-particle")
require("prototypes/entity/optimized-particle/gold-particle")
require("prototypes/entity/optimized-particle/iron-particle")
require("prototypes/entity/optimized-particle/rubber-particle")
require("prototypes/entity/optimized-particle/steel-particle")
require("prototypes/entity/optimized-particle/stone-particle")
require("prototypes/entity/optimized-particle/wood-particle")

require("prototypes/entity/optimized-particle/trailing-bronze-particle")
require("prototypes/entity/optimized-particle/trailing-copper-particle")
require("prototypes/entity/optimized-particle/trailing-glass-particle")
require("prototypes/entity/optimized-particle/trailing-gold-particle")
require("prototypes/entity/optimized-particle/trailing-iron-particle")
require("prototypes/entity/optimized-particle/trailing-rubber-particle")
require("prototypes/entity/optimized-particle/trailing-steel-particle")
require("prototypes/entity/optimized-particle/trailing-stone-particle")
require("prototypes/entity/optimized-particle/trailing-wood-particle")
